### ISSUE TITLE
Not compatible with theme switcher

### ISSUE THREAD

**Issue by fardina** [gurjyot/SnowLight#1]
Hello
Thank you for your theme.

Here you could see the details:
https://github.com/arjunsuresh/q2a-theme-switch/issues/1

 This theme is not compatible with theme switcher plugin.

**Comment by fardina** [comment]
Is there any solution?

**Comment by gurjyot** [comment]
Hello fardina,

Since the theme is changed from Q2A 1.8 SnowFlat theme, I guess there is some problem with backward compatibility. So it's not working on any Q2A version below 1.8. 

So I would suggest to wait for Q2A 1.8 which is going to be released in just a few days.

**Comment by gurjyot** [comment]
I am using this theme on Q2A 1.8 beta-1 for some time now and it's working just fine. Please update your Q2A and let me know if it doesn't work there? Till then I am closing this issue.
